### PR TITLE
add gitlab ci

### PR DESCRIPTION
**Pull request by xiaopeng163**
Thank you for taking the time to work on a PR for Awesome-Open-Source-Supporters!

To ensure your PR is dealt with swiftly please check the following:

- [x] Your submissions are formatted according to the guidelines: ``[Company Name](link) `tag` - description``
- [x] Your additions are ordered alphabetically.
- [ ] Your additions are commercial software that offer their services for free to Open Source projects.
- [ ] Your additions contain any relevant tags: `requires-approval`
- [x] You have searched the repository for any relevant issues or PRs.
- [x] Any category you are creating has the minimum requirement of 2 items.

### CODE REVIEW

**Comment by zachflower** [comment]
Is GitLab CI a separate product from GitLab, or is it a feature offered only to GitLab customers?

**Comment by xiaopeng163** [comment]
GitLab CI is part of GitLab, but if you want to use it, you need to install some additional software like GitLab CI Runner.

**Comment by zachflower** [comment]
Since GitLab CI is a part of GitLab, rather than a separate product in its own right, this appears to be a duplicate (we already call out GitLab in the **Version Control** section). Unless I'm misunderstanding?

**Comment by xiaopeng163** [comment]
yes, but my thought is,  GitLab include in Version Control section, it doesn't mean GitLab can do CI, 

GitHub includes in Version control section, it also can do CI but must be helped by other software like Travis.

**Comment by zachflower** [comment]
I can see where you're coming from, but this list isn't really about highlighting the individual features of individual companies so much as it is highlighting companies that support open source software. That said, if you have a recommendation for a more accurate category to move GitLab under, I'm open to suggestions!

**Comment by xiaopeng163** [comment]
OK, maybe it's my misunderstanding. I just want to highlight that GitLab can do CI. if that is not the point, I will close this PR, thanks anyway.

**Pull request closed without merging**
