### PR TITLE
GitScrum - Manage your Projects Remotely

### PR DESCRIPTION
**Pull request by renatomarinho**
Thank you for taking the time to work on a PR for Awesome-Open-Source-Supporters!

To ensure your PR is dealt with swiftly please check the following:

- [x] Your submissions are formatted according to the guidelines: ``[Company Name](link) `tag` - description``
- [x] Your additions are ordered alphabetically.
- [ ] Your additions are commercial software that offer their services for free to Open Source projects.
- [ ] Your additions contain any relevant tags: `requires-approval`
- [x] You have searched the repository for any relevant issues or PRs.
- [x] Any category you are creating has the minimum requirement of 2 items.

### CODE REVIEW

**Comment by zachflower** [comment]
Hi @renatomarinho, thanks for your submission! I'm looking at the pricing page on the GitScrum website, but I can't seem to find where it is explicitly offered for free to open source projects. Am I missing it somewhere?

**Comment by renatomarinho** [comment]
Hi @zachflower,

I appreciate that you saw the PR.

Today I made the open-source version available, added it to the main menu, and in the footer of the page: https://site.gitscrum.com. We are creating the copy for the site, the repos on GitHub is https://github.com/gitscrum-team/GitScrum-CE

**Comment by zachflower** [comment]
I may be misunderstanding, but it sounds like GitScrum isn't free for open source projects, but instead has an open source Community Edition. Is that correct?

**Comment by renatomarinho** [comment]
Yes, it's correct

**Comment by zachflower** [comment]
I see, okay. Unfortunately, the criteria for inclusion in this list is limited to companies that offer their products for free specifically for open source projects. While companies that offer free tiers—or even their entire product for free—are beneficial, if they don't limit that benefit to open source projects then they don't fit the criteria.

Thank you again for your submission, but since it is out of scope of this project I will mark it as closed. If in the future you expand GitScrum's pricing model to include an explicit offering for open source projects, please do submit again!

**Pull request closed without merging**
